Repository uni-helper/website, pull requests merged in 2025-09, with the labels that each got.

#19 feat(vite-plugin-uni-pages): 扩展路由name的生成
  content/vite-plugin-uni-pages/4.extension/2.page-name.md
Labels: size/M

#20 feat(vite-plugin-uni-pages): 扩展路径常量化
  content/vite-plugin-uni-pages/4.extension.md
  content/vite-plugin-uni-pages/4.extension/1.exclude.md
  content/vite-plugin-uni-pages/4.extension/2.page-name.md
  content/vite-plugin-uni-pages/4.extension/_dir.yml
Labels: size/L

#21 fix(create-uni): nut-uniapp link error and open link in _blank target
  content/create-uni/1.core.md
Labels: size/S
